### ISSUE TITLE
Online Timesheet +Attendance-Tracker Page Day-3

### ISSUE THREAD

**Issue by rajputyash006** [rajputyash006/habitual-hope-140#6]
- [x] Activity Logs Div
- [x] 3 Simple Steps Div
- [x] Comman Footer For All Features Pages Div
- [x] Attendance-Tracker Intro Div
