### ISSUE TITLE
Attendance-Tracker Page Day-4

### ISSUE THREAD

**Issue by rajputyash006** [rajputyash006/habitual-hope-140#7]
- [x] Team Management Functionality Div
- [x] Employee Attendance Tracker Div
- [x] Time Cards For Attendance Div
- [x] Timesheets Complete Div
- [x] Activity Logs Div
- [x] Comman Link Div
